#### Bag of words

### 1.CounVectorzer

In [2]:
text ='My wife likes to watch baseball games and my daughter likes to watch baseball games too.'


In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cvect =CountVectorizer()   #객체 생성
output =cvect.fit_transform([text])
output.toarray()  # toarra가 text 사용한 단어갯수

array([[1, 2, 1, 2, 2, 2, 2, 1, 2, 1]], dtype=int64)

In [6]:
#vocabulary_가 인덱스 위치 알려줌 
cvect.vocabulary_  

{'my': 5,
 'wife': 9,
 'likes': 4,
 'to': 6,
 'watch': 8,
 'baseball': 1,
 'games': 3,
 'and': 0,
 'daughter': 2,
 'too': 7}

- 불용어(Stopwords) 처리

In [9]:
# 직접 지정
my_stopwords =['to','and','my']   #리스트 형식만됨
cvect = CountVectorizer(stop_words=my_stopwords)
print(cvect.fit_transform([text]).toarray())
print(cvect.vocabulary_)

[[2 1 2 2 1 2 1]]
{'wife': 6, 'likes': 3, 'watch': 5, 'baseball': 0, 'games': 2, 'daughter': 1, 'too': 4}


In [10]:
# stop_words='english'를 작성함으로써 Scikit-learn에서 제공하는 불용어 사용
cvect =['to','and','my']  
cvect = CountVectorizer(stop_words='english')
print(cvect.fit_transform([text]).toarray())
print(cvect.vocabulary_)

[[2 1 2 2 2 1]]
{'wife': 5, 'likes': 3, 'watch': 4, 'baseball': 0, 'games': 2, 'daughter': 1}


In [13]:
# NLTK 에서 제공하는 불용어 사용
from nltk.corpus import stopwords
sw =stopwords.words('english')

cvect = CountVectorizer(stop_words=sw)
print(cvect.fit_transform([text]).toarray())
print(cvect.vocabulary_)

[[2 1 2 2 2 1]]
{'wife': 5, 'likes': 3, 'watch': 4, 'baseball': 0, 'games': 2, 'daughter': 1}


- 인덱스에 해당하는 단어를 알려주는 함수

In [14]:
voca =cvect.vocabulary_
for key,value in voca.items():
    print(key,value)

wife 5
likes 3
watch 4
baseball 0
games 2
daughter 1


In [17]:
def get_word(index,voca):
    for key,value in voca.items():
        if value == index:
            return key
get_word(4,cvect.vocabulary_)


'watch'

- #### 3 2. TFIDF(Term Frequency - inverse Document Frequency)

In [18]:
text =['My wife likes to watch baseball games and my daughter likes to watch baseball games too.',
       'MY wife likes to play baseball.']


In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvect =TfidfVectorizer(stop_words='english')
tvect.fit_transform(text).toarray()

array([[0.38649245, 0.27160082, 0.54320165, 0.38649245, 0.        ,
        0.54320165, 0.19324622],
       [0.44832087, 0.        , 0.        , 0.44832087, 0.63009934,
        0.        , 0.44832087]])

In [22]:
print(tvect.vocabulary_)

{'wife': 6, 'likes': 3, 'watch': 5, 'baseball': 0, 'games': 2, 'daughter': 1, 'play': 4}


In [23]:
cvect =CountVectorizer(stop_words='english')
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[2 1 2 2 0 2 1]
 [1 0 0 1 1 0 1]]
{'wife': 6, 'likes': 3, 'watch': 5, 'baseball': 0, 'games': 2, 'daughter': 1, 'play': 4}


In [24]:
#### 3.N - gram

In [25]:
text =['I wordk at goole.' 'I google at work.']
cvect =CountVectorizer()
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[2 1 1 1 1]]
{'wordk': 3, 'at': 0, 'goole': 2, 'google': 1, 'work': 4}


In [29]:
#ngram_range=(1, 1)은 단일 단어만을 추출하고,
#ngram_range=(1, 2)는 단일 단어와 두 개의 연속된 단어를 추출합니다
cvect =CountVectorizer(ngram_range=(1,2)) 
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[2 1 1 1 1 1 1 1 1 1]]
{'wordk': 7, 'at': 0, 'goole': 5, 'google': 3, 'work': 9, 'wordk at': 8, 'at goole': 1, 'goole google': 6, 'google at': 4, 'at work': 2}


##### 4. Hyper parameter

In [27]:
cvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 2),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [28]:
tvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': 'english',
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}