#### 컨텐츠 기반 필터링(Conents-based filtering)

In [1]:
# 라이브러리 설치
!pip install scikit-surprise

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 772.0/772.0 kB 24.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.3-cp310-cp310-linux_x86_64.whl size=3095456 sha256=6b87641dcf81d34937e9357decdd7fbbbfdef7e27078b3405082a2ee42b8c873
  Stored in directory: /root/.cache/pip/wheels/a5/ca/a8/4e28def53797fdc4363ca4af740db15a9c2f1595ebc51fb445
Successfully built scikit-surprise


In [2]:
import numpy as np
import pandas as pd
from surprise import Dataset

In [3]:
data =Dataset.load_builtin('ml-100k',prompt =False)
df =pd.DataFrame(data.raw_ratings,columns=['user-id','movie-id','rating','timestamp'])
df.head()

Trying to download dataset from https://files.grouplens.org/datasets/movielens/ml-100k.zip...
Done! Dataset ml-100k has been saved to /root/.surprise_data/ml-100k


user-id movie-id  rating  timestamp
0     196      242     3.0  881250949
1     186      302     3.0  891717742
2      22      377     1.0  878887116
3     244       51     2.0  880606923
4     166      346     1.0  886397596

In [4]:
df.shape,df['user-id'].nunique(),df['movie-id'].nunique()

((100000, 4), 943, 1682)

#####1. Adjacent Matrix 생성
- 행 :  사용자 id
- 열 : 영화 id
- 내용 : 평점

In [5]:
raw_data =np.array(data.raw_ratings,dtype =int)
np.min(raw_data,axis=0)     # 각 컬럼 최소값 보여줌 

array([        1,         1,         1, 874724710])

In [6]:
# user -id movie-id가 0부터 시작도록 만들어줌
raw_data[:,:2]-=1      #정수로 바꿔줌
raw_data[:5]
# 일반적으로 사용되는 인덱스가 0부터 시작
# 대부분의 프로그래밍 언어 및 라이브러리는 0부터 인덱싱 든 값들을 1씩 감소시킴

array([[      195,       241,         3, 881250949],
       [      185,       301,         3, 891717742],
       [       21,       376,         1, 878887116],
       [      243,        50,         2, 880606923],
       [      165,       345,         1, 886397596]])

In [7]:
np.min(raw_data)

0

#### 1) 본 영화/안본 영화로만 구분. 1/0 

In [8]:
nrows = df['user-id'].nunique()
ncols=df['movie-id'].nunique()
adj_matrix =np.zeros([nrows,ncols],dtype =int)
for user_id,movie_id,_,_ in raw_data:
  adj_matrix[user_id,movie_id] = 1
adj_matrix[:5]

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]])

In [9]:
# 0번 데이터를 '나'라고 가정
my_id, my_vector =0 ,adj_matrix[0]

In [10]:
# 유사도  - 이진 백터의 내적
# 나(0번)와 10,20번 사용자와의 유사도 점수
np.dot(my_vector,adj_matrix[10]),np.dot(my_vector,adj_matrix[20])


(71, 42)

- 내적 계산 하는방법
- a = np.array([1, 2, 3])
- b = np.array([4, 5, 6])
- dot_product = np.dot(a, b)
- (1 * 4) + (2 * 5) + (3 * 6) = 4 + 10 + 18 = 32

In [11]:
# 누가 나랑 가장 닮았나?
best_score,best_match_id =0,0

# 최대값 찾는 방법
for i in range(1,len(adj_matrix)):
  #np.dot(a, b)는 배열 a와 b의 내적을 계산하는 함수
  dot=np.dot(my_vector,adj_matrix[i])
  if dot > best_score:
    best_score,best_match_id =dot ,i
best_score,best_match_id 

(183, 275)

In [12]:
# 내가 본 영화 갯수, 가장 닮은 사람이 본 영화 갯수
my_vector.sum(),adj_matrix[best_match_id].sum()      # 나는 272개 보고 나랑 닮은 사람은 518번 봄

(272, 518)

In [13]:
# 내가 보지 않은 영화중에서 가장 닮은 사람이 본 영화 --> 추천
recommend_list =[]
best_vector =adj_matrix[best_match_id]
for i in range(len(my_vector)):
  if my_vector[i] == 0 and best_vector[i] == 1:
    recommend_list.append(i)
  
len(recommend_list),recommend_list[:10]

(335, [272, 273, 275, 280, 281, 283, 287, 288, 289, 290])

#### 2) 평점 점수를 주는 경우

In [14]:
adj_matrix =np.zeros([nrows,ncols],dtype=int)
for user_id,movie_id,rating,_ in raw_data:
  adj_matrix[user_id,movie_id] = rating
adj_matrix[:5]
# 평점으로 추천

array([[5, 3, 4, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [4, 3, 0, ..., 0, 0, 0]])

- Case 1) 유클리드 거리

In [15]:
#누가 가장 나와 닮았나? 최소값이 작은사람 
best_score,best_match_id =1000000000,0
my_vector =adj_matrix[0]

for i in range(1,len(adj_matrix)):
  euc =np.sqrt(np.sum(np.square(my_vector - adj_matrix[i])))
  if euc < best_score:
    best_score,best_match_id =euc ,i
best_score,best_match_id 
# 737번 아이디가 나랑 닮음

(55.06359959174482, 737)

In [16]:
# 내가 보지 않은 영화중에서 가장 닮은 사람이 본 영화 --> 추천
recommend_list =[]
best_vector =adj_matrix[best_match_id]
for i in range(len(my_vector)):
  if my_vector[i] == 0 and best_vector[i] >= 4: #내가 안본 영화를 닮은사람이 보고 평점을 4이하를 줬으면 추천안받고 싶음
    recommend_list.append(i)
len(recommend_list),recommend_list[:10]
# 21건이 나옴

(21, [312, 317, 356, 384, 407, 422, 433, 454, 469, 473])

- Case 2) 코사인 유사도

In [17]:
def cos_similarity(v1,v2):
  v1_norm =np.sqrt(np.sum(np.square(v1)))
  v2_norm =np.sqrt(np.sum(np.square(v2)))
  return np.dot(v1,v2) / (v1_norm * v2_norm)

In [18]:
# 누가 가장 '나'와 닮았나? - Cosine similarity 최대값
best_score, best_match_id = -1, 0

for i in range(1, len(adj_matrix)):
  sim = cos_similarity(my_vector, adj_matrix[i])
  if sim > best_score:
    best_score, best_match_id = sim, i
  
best_score, best_match_id

(0.569065731527988, 915)

In [19]:
# 내가 보지 않은 영화중에서 가장 닮은 사람이 본 영화중 평점이 4이상인 영화 --> 추천
recommend_list = []
best_vecotr = adj_matrix[best_match_id]
for i in range(len(my_vector)):
  if my_vector[i] == 0 and best_vecotr[i] >= 4:
    recommend_list.append(i)

len(recommend_list), recommend_list[:10] 

(58, [275, 285, 316, 317, 381, 386, 420, 424, 426, 427])